name: Publish interface package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  PROJECT: Hasselman.Backsplice.Spreadsheet
  OWNER: james-d-hasselman

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: "Build $PROJECT"
      run: dotnet build --no-restore

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
          source-url: "https://nuget.pkg.github.com/$OWNER/index.json"
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Create the package
        run: dotnet pack --configuration Release $PROJECT
      - name: Publish the package to GPR
        run: dotnet nuget push $PROJECT/bin/Release/*.nupkg
