name: Publish interface package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: "Build Hasselman.Backsplice.Spreadsheet"
      run: dotnet build --no-restore

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
      - name: Authenticate to GitHub Packages
        run: dotnet nuget add source --username james-d-hasselman --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/james-d-hasselman/index.json"
      - name: Create the package
        run: dotnet pack --configuration Release Hasselman.Backsplice.Spreadsheet
      - name: Publish the package to GPR
        run: dotnet nuget push Hasselman.Backsplice.Spreadsheet/bin/Release/*.nupkg --api-key ${{secrets.TOKEN}} --source "github"
