name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
         dotnet-version: 6.0.x
      - run: dotnet pack --configuration Release
      - name: Authenticate with GitHub Packages
        run: dotnet nuget add source --username james-d-hasselman --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/james-d-hasselman/index.json"
      - run: dotnet nuget push "bin/Release/OctocatApp.1.0.0.nupkg"  --api-key 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 --source "github"
